### ISSUE TITLE
Make the list of banned users configurable

### ISSUE THREAD

**Issue by abompard** [fedora-infra/fedbadges#99]
In `fedbadges/rules.py`, there's a list of banned users that should be skipped when awarding badges. This should be in the configuration (and please rename it to `skip_users`, we don't actually "ban" bodhi or pagure).

**Comment by jeffiscow2** [comment]
I'm new to all this, and I'd really like to help because I love collecting the fedora badges.

If I understand this issue correctly, is it asking to just have the "banned_usernames" variable name changed to "skip_users"? I'm not sure what "make a list of banned users configurable" means. Configurable how? Is there some type of command line tool, or is there a UI I'd need to tie this into for that?

Thanks for any guidance you can give.

I've read a bunch of the documentation on the badges rewrite still wrapping my head around it all.

**Comment by penguinpee** [comment]
If you look at

https://github.com/fedora-infra/fedbadges/blob/a230c7525d1e4c8137a4660c81227a64f601a1fb/fedbadges/rules.py#L93-L110

you can see the list of "banned" users is statically maintained in the code. My guess is that should be runtime configurable (e.g. maintained in and read from a config file or such). I'm not sure what runtime configuration is currently used. I guess some Python or YAML file. Aurélien will know for sure.

The name of that parameter should be `skip_users` instead of `banned_usernames`.

Thanks for taking a deep dive!

**Comment by jeffiscow2** [comment]
> 
> you can see the list of "banned" users is statically maintained in the code. My guess is that should be runtime configurable (e.g. maintained in and read from a config file or such). I'm not sure what runtime configuration is currently used. I guess some Python or YAML file. Aurélien will know for sure.
> 

I'll look into the documentation about runtime configuration and see if I can figure it out while I wait for confirmation. Thanks again!

**Comment by jeffiscow2** [comment]
Looks like I found my answer by looking at the readme lol. I just assumed it was the same kinda stuff from https://fedora-arc.readthedocs.io/en/latest/badges/index.html.

smh

**Comment by abompard** [comment]
Hey @jeffiscow2 ! The configuration for the consumer is in the Fedora Messaging TOML file ([described here](https://fedora-messaging.readthedocs.io/en/stable/user-guide/configuration.html#id16)). There's an example in `fedbadges.toml.example` at the root of the repo, and there's the one used by the Vagrant development environment in `devel/ansible/roles/dev/files/config.toml`.

The content of the `consumer_config` dict is available in `Rule` objects as `self.config`, so you can use that.
Let me know if you have any questions!

**Comment by abompard** [comment]
Hey @jeffiscow2 , are you still interested in working on this?

**Comment by jeffiscow2** [comment]
@abompard yeah I am. Just got busy for a bit with the kids starting school and even after reading everything I'm still lost. I'll need more guidance for sure, lol.

**Comment by abompard** [comment]
Sure, just ask when you're ready.

**Comment by jeffiscow2** [comment]
I made some modifications to rules.py (changed the BadgesRule class) and created a skip_users.toml with the list of skipped usernames.

Let me know if I'm on the right track. I should be home all day to respond if you need to tell me anything.

https://github.com/jeffiscow2/fedbadges

**Comment by abompard** [comment]
Could you create a draft pull request? It would make reviewing easier. Thanks!

Also, you can use the `[consumer_config]` section in the main config file instead of adding a new one.
